import { describe, expect, it } from 'vitest';

import { parseDocument } from './document';
import { dimensionFrame } from './elements';
import { SCHEMA_VERSION } from './types';

/**
 * Fixtures for every schema version that has ever been written.
 *
 * These are deliberately literal — hand-written JSON rather than something built by the
 * current factories — because the whole point is to hold on to what an *older* Hashira
 * actually put in the database. A fixture generated by today's code would migrate itself
 * quietly and prove nothing.
 */

/** A version 1 drawing: one wall, one door hosted on it, and a room label. */
const VERSION_1 = {
    schemaVersion: 1,
    id: '01hxyz000000000000000000',
    name: 'Before dimensions',
    settings: {
        unit: 'm',
        scale: 50,
        grid: { size: 100, subdivisions: 2, visible: true, snap: true },
        snapping: { enabled: true, endpoint: true, midpoint: true, intersection: true, axis: true },
        sheet: { size: 'A3', orientation: 'landscape' },
        title: 'Before dimensions',
    },
    layers: [
        {
            id: 'layer_architecture',
            name: 'Architecture',
            color: '#1F2328',
            visible: true,
            locked: false,
            order: 0,
        },
        {
            id: 'layer_openings',
            name: 'Openings',
            color: '#1F2328',
            visible: true,
            locked: false,
            order: 1,
        },
        {
            id: 'layer_annotations',
            name: 'Annotations',
            color: '#5F636B',
            visible: true,
            locked: false,
            order: 4,
        },
    ],
    elements: [
        {
            id: 'el_wall',
            type: 'wall',
            layerId: 'layer_architecture',
            transform: { x: 3000, y: 0, rotation: 0 },
            geometry: { a: { x: -3000, y: 0 }, b: { x: 3000, y: 0 }, thickness: 150 },
            metadata: { createdAt: '2026-01-01T00:00:00.000Z' },
        },
        {
            id: 'el_door',
            type: 'door',
            layerId: 'layer_openings',
            transform: { x: 0, y: 0, rotation: 0 },
            geometry: {
                hostId: 'el_wall',
                offset: 1200,
                width: 900,
                swing: 'left',
                flipped: false,
            },
            metadata: { createdAt: '2026-01-01T00:00:00.000Z' },
        },
        {
            id: 'el_label',
            type: 'text',
            layerId: 'layer_annotations',
            transform: { x: 3000, y: 1500, rotation: 0 },
            geometry: { content: 'Living', fontSize: 250, align: 'center' },
            metadata: { createdAt: '2026-01-01T00:00:00.000Z' },
        },
    ],
};

describe('opening a version 1 drawing', () => {
    it('opens', () => {
        expect(parseDocument(VERSION_1).ok).toBe(true);
    });

    it('keeps every element, losing nothing to the newer schema', () => {
        const parsed = parseDocument(VERSION_1);

        expect(parsed.ok && parsed.dropped).toEqual([]);
        expect(parsed.ok && parsed.document.elements.map((element) => element.id)).toEqual([
            'el_wall',
            'el_door',
            'el_label',
        ]);
    });

    it('keeps the geometry exactly as it was written', () => {
        const parsed = parseDocument(VERSION_1);
        const wall = parsed.ok ? parsed.document.elements[0] : undefined;

        expect(wall?.type === 'wall' && wall.geometry).toEqual({
            a: { x: -3000, y: 0 },
            b: { x: 3000, y: 0 },
            thickness: 150,
        });
    });

    it('keeps a door pointing at the wall it was cut into', () => {
        const parsed = parseDocument(VERSION_1);
        const door = parsed.ok ? parsed.document.elements[1] : undefined;

        expect(door?.type === 'door' && door.geometry.hostId).toBe('el_wall');
    });

    it('comes back stamped with the current schema, ready to be saved again', () => {
        const parsed = parseDocument(VERSION_1);

        expect(parsed.ok && parsed.document.schemaVersion).toBe(SCHEMA_VERSION);
    });

    it('keeps its layers, including the ones it happened not to have', () => {
        const parsed = parseDocument(VERSION_1);

        // A version 1 drawing predates nothing about layers, so what it had is what it keeps —
        // the migration does not go inventing a dimensions layer it never used.
        expect(parsed.ok && parsed.document.layers.map((layer) => layer.id)).toEqual([
            'layer_architecture',
            'layer_openings',
            'layer_annotations',
        ]);
    });
});

/** A version 2 drawing: the same wall, with the measurement that version 2 could write. */
const VERSION_2 = {
    ...VERSION_1,
    schemaVersion: 2,
    name: 'Before chains',
    elements: [
        ...VERSION_1.elements,
        {
            id: 'el_dimension',
            type: 'dimension',
            layerId: 'layer_dimensions',
            transform: { x: 3000, y: 0, rotation: 0 },
            geometry: {
                a: { x: -3000, y: 0 },
                b: { x: 3000, y: 0 },
                offset: 800,
                fontSize: 200,
            },
            metadata: { createdAt: '2026-02-01T00:00:00.000Z' },
        },
    ],
};

describe('opening a version 2 drawing', () => {
    it('opens, keeping the measurement it was written with', () => {
        const parsed = parseDocument(VERSION_2);

        expect(parsed.ok).toBe(true);
        expect(parsed.ok && parsed.dropped).toEqual([]);
        expect(parsed.ok && parsed.document.elements.map((element) => element.id)).toContain(
            'el_dimension',
        );
    });

    /*
     * Version 3 measures a run of points rather than a pair of them. Every dimension ever
     * written has exactly two, which is a chain of one — so the step is a rewrite of the
     * shape and not of the measurement.
     */
    it('reads its two measured points as the run they always were', () => {
        const parsed = parseDocument(VERSION_2);
        const dimension = parsed.ok
            ? parsed.document.elements.find((element) => element.id === 'el_dimension')
            : undefined;

        expect(dimension?.type === 'dimension' && dimension.geometry).toEqual({
            points: [
                { x: -3000, y: 0 },
                { x: 3000, y: 0 },
            ],
            offset: 800,
            fontSize: 200,
        });
    });

    it('still measures the same six metres it did before', () => {
        const parsed = parseDocument(VERSION_2);
        const dimension = parsed.ok
            ? parsed.document.elements.find((element) => element.id === 'el_dimension')
            : undefined;

        expect(dimension?.type === 'dimension' ? dimensionFrame(dimension)?.length : null).toBe(
            6000,
        );
    });

    it('comes back stamped with the current schema, ready to be saved again', () => {
        const parsed = parseDocument(VERSION_2);

        expect(parsed.ok && parsed.document.schemaVersion).toBe(SCHEMA_VERSION);
    });
});

describe('a drawing from a newer Hashira', () => {
    it('is refused outright rather than opened with pieces missing', () => {
        const parsed = parseDocument({ ...VERSION_1, schemaVersion: SCHEMA_VERSION + 1 });

        expect(parsed.ok).toBe(false);
        expect(!parsed.ok && parsed.reason).toContain('newer version');
    });
});
